services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '80'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test:
        - CMD
        - wget
        - '--quiet'
        - '--tries=1'
        - '--spider'
        - 'http://localhost'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.http.routers.hcm202.rule=Host(`hcm202.smartnovi.tech`)
      - traefik.http.routers.hcm202.entrypoints=websecure
      - traefik.http.routers.hcm202.tls=true
      - traefik.http.routers.hcm202.tls.certresolver=letsencrypt
      - traefik.http.services.hcm202.loadbalancer.server.port=80
    networks:
      - coolify

networks:
  coolify:
    external: true
